name: DcDc2
favicon: null
layout_spectrum: 0.27722
typography_spectrum: 0.30583
title: Kitesurfing in Hampshire
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2406860333867371
  lightness: 0.42883620387874544
  saturation: 0.9253504779189825
  rhythmicContrast: 0.9755455756094307
purpose: []
